// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjSEb4Zt1aiE7L-JEOu3EHtGdqjIAhK0',
    appId: '1:824438797670:web:bbf999bd53cf87a1ef04a7',
    messagingSenderId: '824438797670',
    projectId: 'real-mobile-number-app',
    authDomain: 'real-mobile-number-app.firebaseapp.com',
    storageBucket: 'real-mobile-number-app.firebasestorage.app',
    measurementId: 'G-ZBYKT3NHMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjSEb4Zt1aiE7L-JEOu3EHtGdqjIAhK0',
    appId: '1:824438797670:android:bbf999bd53cf87a1ef04a7',
    messagingSenderId: '824438797670',
    projectId: 'real-mobile-number-app',
    storageBucket: 'real-mobile-number-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjSEb4Zt1aiE7L-JEOu3EHtGdqjIAhK0',
    appId: '1:824438797670:ios:bbf999bd53cf87a1ef04a7',
    messagingSenderId: '824438797670',
    projectId: 'real-mobile-number-app',
    storageBucket: 'real-mobile-number-app.firebasestorage.app',
    iosBundleId: 'com.example.serviceAppMobile',
  );
}
